import { Product, SiteConfig } from './types';

// Imagens em public/assets/ — URLs estáveis sem hash, seguras para salvar no Firestore.
// Nunca usar static import para assets referenciados em banco de dados.

export const SHOP_INFO: SiteConfig = {
  shopName: 'Ótica Roland',
  whatsapp: '5511998793053',
  address: 'Av. Domingos de Morais, 138, Vila Mariana, SP',
  workingHours: {
    weekdays: '10h às 17h',
    saturday: '10h às 14h',
  },
  heroTitle: 'Refine o seu olhar.',
  heroSubtitle:
    'A união do rigor técnico com a curadoria de design. Peças selecionadas para quem busca conforto e distinção.',
};

export const IMAGES = {
  hero: '/assets/aviador.png',
  // Placeholder — substituir pela foto real do Sr. Walter ou da loja
  story: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=900',
};

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'ray-ban-aviator',
    name: 'Ray-Ban Aviador Clássico',
    price: 420,
    description: 'Armação metal dourada com lentes G-15. Ícone atemporal.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 0,
    tags: ['solar', 'masculino', 'metal', 'classico'],
  },
  {
    id: 'ray-ban-wayfarer',
    name: 'Ray-Ban Wayfarer',
    price: 390,
    description: 'Acetato preto com lentes polarizadas. O mais icônico do mundo.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 1,
    tags: ['solar', 'masculino', 'acetato', 'classico'],
  },
  {
    id: 'oakley-holbrook',
    name: 'Oakley Holbrook',
    price: 580,
    description: 'Acetato resistente com lentes Prizm para máxima definição de cores.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 2,
    tags: ['solar', 'masculino', 'acetato', 'esportivo', 'premium'],
  },
  {
    id: 'carrera-metal',
    name: 'Carrera Champion Metal',
    price: 510,
    description: 'Armação metal 3 peças com hastes ajustáveis. Design italiano.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 3,
    tags: ['solar', 'masculino', 'metal', '3-pecas', 'italiano'],
  },
  {
    id: 'chanel-cat-eye',
    name: 'Cat Eye Premium',
    price: 650,
    description: 'Acetato com detalhe dourado. Elegância feminina atemporal.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1483304528321-0674f0040030?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 4,
    tags: ['solar', 'feminino', 'acetato', 'cat-eye', 'premium'],
  },
  {
    id: 'gucci-oversized',
    name: 'Oversized Glamour',
    price: 720,
    description: 'Armação oversized em acetato tortoise. Estilo e proteção máximos.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1494582378537-5da4db80f701?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 5,
    tags: ['solar', 'feminino', 'acetato', 'oversized', 'premium'],
  },
  {
    id: 'prada-round',
    name: 'Round Vintage Feminino',
    price: 480,
    description: 'Armação redonda em metal rose gold. Delicada e moderna.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 6,
    tags: ['solar', 'feminino', 'metal', 'redondo', 'vintage'],
  },
  {
    id: 'tiffany-butterfly',
    name: 'Butterfly Acetato',
    price: 545,
    description: 'Formato borboleta em acetato bicolor. Peça de destaque.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 7,
    tags: ['solar', 'feminino', 'acetato', 'butterfly'],
  },
  {
    id: 'zeiss-vr-one',
    name: 'Zeiss VR ONE Plus',
    price: 750,
    description: 'Tecnologia Zeiss com lentes de alta performance visual.',
    quantity: 3,
    imageUrl: '/assets/vrone.png',
    isConsultative: false,
    active: true,
    order: 8,
    tags: ['solar', 'unissex', 'premium', 'tecnologia'],
  },
  {
    id: 'aviador-sky',
    name: 'Aviador Sky Edition',
    price: 280,
    description: 'Leveza e proteção com lentes polarizadas de alta definição.',
    quantity: 5,
    imageUrl: '/assets/aviador-solar.png',
    isConsultative: false,
    active: true,
    order: 9,
    tags: ['solar', 'unissex', 'metal', 'aviador'],
  },
  {
    id: 'titanium-slim',
    name: 'Titanium Slim',
    price: 890,
    description: 'Titânio puro ultraleve. Flexível, hipoalergênico e durável.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 10,
    tags: ['grau', 'masculino', 'titanium', 'premium', 'leve'],
  },
  {
    id: 'acetato-bold',
    name: 'Acetato Bold Masculino',
    price: 320,
    description: 'Armação acetato com estrutura robusta. Personalidade e estilo.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 11,
    tags: ['grau', 'masculino', 'acetato', 'moderno'],
  },
  {
    id: 'metal-3pecas',
    name: 'Metal 3 Peças Clássico',
    price: 410,
    description: 'Armação 3 peças em metal com ponte ajustável. Elegante e preciso.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 12,
    tags: ['grau', 'masculino', 'metal', '3-pecas', 'classico'],
  },
  {
    id: 'acetato-feminino',
    name: 'Acetato Floral Feminino',
    price: 298,
    description: 'Acetato com padrão floral sutil. Delicado e sofisticado.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1600091166971-7f9faad6c498?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 13,
    tags: ['grau', 'feminino', 'acetato', 'delicado'],
  },
  {
    id: 'titanium-feminino',
    name: 'Titanium Fio Feminino',
    price: 760,
    description: 'Fio de nylon com titânio. Quase invisível no rosto.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 14,
    tags: ['grau', 'feminino', 'titanium', 'fio-de-nylon', 'premium'],
  },
  {
    id: 'gatinho-acetato',
    name: 'Gatinho Acetato Premium',
    price: 345,
    description: 'Clássico gatinho em acetato bicolor. Charme e personalidade.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 15,
    tags: ['grau', 'feminino', 'acetato', 'gatinho'],
  },
  {
    id: 'kids-flex',
    name: 'Kids Flex Inquebrável',
    price: 220,
    description: 'Memória de forma flexível. Resiste a quedas e brincadeiras.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 16,
    tags: ['grau', 'infantil', 'flex', 'resistente'],
  },
  {
    id: 'kids-solar',
    name: 'Solar Kids UV400',
    price: 180,
    description: 'Proteção UV400 em armação leve e colorida para crianças.',
    quantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 17,
    tags: ['solar', 'infantil', 'uv400', 'colorido'],
  },
  {
    id: 'acuvue-oasys',
    name: 'ACUVUE® OASYS HYDRACLEAR®',
    price: 260,
    description: 'Hidratação contínua para máximo conforto diário.',
    quantity: 10,
    imageUrl: '/assets/oasis.png',
    isConsultative: true,
    active: true,
    order: 18,
    tags: ['lentes', 'conforto', 'quinzenal'],
  },
  {
    id: 'acuvue-moist',
    name: 'Acuvue Moist 1-Day',
    price: 265,
    description: 'Praticidade e saúde ocular em descarte diário.',
    quantity: 8,
    imageUrl: 'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?auto=format&fit=crop&q=80&w=800',
    isConsultative: true,
    active: true,
    order: 19,
    tags: ['lentes', 'diario', 'descartavel'],
  },
  {
    id: 'zeiss-wipes',
    name: 'Zeiss Lens Wipes',
    price: 99,
    description: 'Lenços de limpeza óptica profissional.',
    quantity: 20,
    imageUrl: '/assets/lens-wipes.png',
    isConsultative: false,
    active: true,
    order: 20,
    tags: ['acessorios', 'limpeza', 'zeiss'],
  },
  {
    id: 'solucao-care',
    name: 'Solução Care+ Multipropósito',
    price: 85,
    description: 'Cuidado completo para lentes de contato.',
    quantity: 15,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    isConsultative: false,
    active: true,
    order: 21,
    tags: ['acessorios', 'lentes', 'cuidado'],
  },
];
